[project]
name = "day13"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llvmlite>=0.46.0",
    "numba>=0.63.1",
    "pandas>=2.3.3",
    "snowflake-ml-python>=1.22.0",
    "snowflake-snowpark-python>=1.44.0",
    "streamlit>=1.53.0",
]
